version: "3.8"
services:
  nginx:
    image: nginx:1.18.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./apps:/var/www/html
    restart: always
  mysql:
    image: mysql:5.7.12
    container_name: mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: always
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: aws_php:latest
    container_name: php
    ports:
      - "9000:9000"
    volumes:
        - ./apps:/var/www/html
        - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
networks:
  default:
    external:
      name: proxy